/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kronemetree;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author ebubekir
 */
public class Kronemetre extends javax.swing.JFrame {

    /**
     * Creates new form Kronemetre
     */
    public Kronemetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button1 = new java.awt.Button();
        txtsny = new javax.swing.JLabel();
        txtdkk = new javax.swing.JLabel();
        txtsaat = new javax.swing.JLabel();
        txtsaat2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ebubekir Bastama Kronometre");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Başlat");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Durdur");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        button1.setBackground(new java.awt.Color(51, 51, 51));
        button1.setLabel("Temizle");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        txtsny.setBackground(new java.awt.Color(0, 0, 0));
        txtsny.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsny.setForeground(new java.awt.Color(51, 0, 0));
        txtsny.setText("0");

        txtdkk.setBackground(new java.awt.Color(0, 0, 0));
        txtdkk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdkk.setForeground(new java.awt.Color(255, 0, 0));
        txtdkk.setText("0");

        txtsaat.setBackground(new java.awt.Color(0, 0, 0));
        txtsaat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsaat.setForeground(new java.awt.Color(255, 0, 0));
        txtsaat.setText("0");

        txtsaat2.setBackground(new java.awt.Color(0, 0, 0));
        txtsaat2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsaat2.setForeground(new java.awt.Color(255, 0, 0));
        txtsaat2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(txtsaat2)
                .addGap(53, 53, 53)
                .addComponent(txtsaat)
                .addGap(53, 53, 53)
                .addComponent(txtdkk)
                .addGap(56, 56, 56)
                .addComponent(txtsny)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsaat)
                    .addComponent(txtsaat2)
                    .addComponent(txtdkk)
                    .addComponent(txtsny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int sny = 0; 
  int dkka= 0;
  int Saat= 0;
  int Aslsaat=0;
  Boolean drm = true;
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        drm=false;
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       try{
           drm=true;
          Timer timer = new Timer(); 
          TimerTask task = new TimerTask() {
            @Override
            public void run() {
                if (drm==false) {
                   timer.cancel();
                }
                sny++;
                txtsny.setText(Integer.toString(sny));
                if (sny==60) {
                    dkka++;
                    txtdkk.setText(Integer.toString(dkka));
                    sny=0;
                    if(dkka==60){
                        Saat++;
                        txtsaat.setText(Integer.toString(Saat));
                        dkka=0;
                    }
                    if(Saat==60){
                        Aslsaat++;
                        txtsaat2.setText(Integer.toString(Aslsaat));
                        Saat=0;
                    }
                }
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 10); 
     }
     catch(Exception ex)
     {
     JOptionPane.showMessageDialog(null, ex.getMessage() ,"Hata", 1);
     }
    }//GEN-LAST:event_jButton1MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        txtsny.setText("0");
        txtdkk.setText("0");
        txtsaat.setText("0");
        txtsaat2.setText("0");
        sny = 0;
        dkka= 0;
        Saat= 0;
        Aslsaat=0;
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kronemetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kronemetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kronemetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kronemetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kronemetre().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private java.awt.Panel panel2;
    private javax.swing.JLabel txtdkk;
    private javax.swing.JLabel txtsaat;
    private javax.swing.JLabel txtsaat2;
    private javax.swing.JLabel txtsny;
    // End of variables declaration//GEN-END:variables
}
